<?php
// Variables
return [
  "creatorName" => "CZ App Studio",
  "creatorUrl" => "https://czappstudio.com/",
  "supportNumber" => "+91 88254 29360",
  "supportWhatsappURL" => "https://wa.me/+918825429360",
  "supportEmail" => "support@czappstudio.com",
  "templateName" => "Open Core HR",
  "templateFullName" => "Open Core HR",
  "templateSuffix" => "SaaS",
  "templateVersion" => "4.2.0",
  "templateFree" => false,
  "templateDescription" => "AI-Driven HRMS for Modern Businesses.",
  "templateKeyword" => "HRMS, HR, Management, System, Application, Software, Employee, Leave, Attendance, Payroll, Recruitment, Performance, Appraisal, Training, Development, Expense, Management, Task, Project, Team, Collaboration, Communication, Notification, Workflow, Automation, Reporting, Analytics, Dashboard, Admin, Panel",
  "licenseUrl" => "https://czappstudio.com/license/",
  "livePreview" => "https://czappstudio.com",
  "productPage" => "https://codecanyon.net/item/fieldmanager-saas-hrms-employees-gps-realtime-tracking-attendance-payroll-system-net-flutter/45820223",
  "support" => "https://czappstudio.com/support/",
  "activationDocs" => "https://czappstudio.com/docs/open-core-hr/product-activation/",
  "moreThemes" => "https://czappstudio.com",
  "documentation" => "https://czappstudio.com/docs/open-core-hr/",
  "changelog" => "https://czappstudio.com",
  "repository" => "https://czappstudio.com",
  "gitRepo" => "https://czappstudio.com",
  "gitRepoAccess" => "https://czappstudio.com",
  "githubFreeUrl" => "https://czappstudio.com",
  "facebookUrl" => "https://czappstudio.com",
  "twitterUrl" => "https://czappstudio.com",
  "githubUrl" => "https://czappstudio.com",
  "dribbbleUrl" => "https://czappstudio.com",
  "instagramUrl" => "https://www.instagram.com/czappstudio/",
  'linkedInUrl' => 'https://in.linkedin.com/company/cz-app-studio',
  'youtubeUrl' => 'https://www.youtube.com/@CZAppStudio',
  'appDemoLink' => 'https://play.google.com/store/apps/details?id=com.czappstudio.open_core_hr',
  'superAdminPanelDemoLink' => 'https://opencorehr.com/',
  'adminPanelDemoLink' => 'https://testdomain.opencorehr.com/',
  'itemId' => 8861,
  'envatoItemId' => 45820223,
];
